<div class="field-bg">
	<h2 class="title-page-name text-center">О нас</h2>
</div>
<div class="band-photo">
	<figure>
		<img src="/img/usova.jpg">
		<figcaption>Юлия Усова</figcaption>
	</figure>
	<figure>
		<img src="/img/timur.jpg">
		<figcaption>Тимур Сигидин</figcaption>
	</figure>
	<figure>
		<img src="/img/belkin.jpg">
		<figcaption>Алексей Белкин</figcaption>
	</figure>
	<figure>
		<img src="/img/petja.jpg">
		<figcaption>Пётр Сергеев</figcaption>
	</figure>
	<figure>
		<img src="/img/shixard.jpg">
		<figcaption>Дмитрий Шихардин</figcaption>
	</figure>
	<figure>
		<img src="/img/skos.jpg">
		<figcaption>Алексей Скоссырев</figcaption>
	</figure>
</div>
<div class="field-bg">
<p>Группа «Отава ё» появилась на свет абсолютно спонтанно примерно в 2003 году, правда тогда мы еще не знали, что это будет самостоятельный коллектив:
</p><p>
Мы все были заняты в разных группах, и «Отава ё» стала своего рода реализацией того, что нам не удавалось делать в своих основных проектах.
</p><p>
Мы стараемся не быть очень серьезными, так что если вам покажется, что вы слышите что-то такое, чего никак не ожидали услышать, то это именно то, чего мы и добивались.
</p>
</div>