<section class="field-bg">
	<h2 class="title-page-name text-center"><?= $this->translate('page.title.band'); ?></h2>

	<div class="band-photo">
		<figure>
			<figcaption><?= $this->translate('band.name.belkin'); ?><br/><?= $this->translate('band.name.belkin_desc'); ?></figcaption>
			<img src="/img/band/83DDEMt1D14.jpg" alt="фото Алексея Белкина">
		</figure>
		<figure>
			<figcaption><?= $this->translate('band.name.dima'); ?><br/><?= $this->translate('band.name.dima_desc'); ?></figcaption>
			<img src="/img/band/WLHO4ULquYk.jpg" alt="фото Дмитрия Шихардина">
		</figure>
		<figure>
			<figcaption><?= $this->translate('band.name.petia'); ?><br/><?= $this->translate('band.name.petia_desc'); ?></figcaption>
			<img src="/img/band/AJCON7Uvk_4.jpg" alt="фото Петра Сергеева">
		</figure>
		<figure>
			<figcaption><?= $this->translate('band.name.aleksey'); ?><br/><?= $this->translate('band.name.aleksey_desc'); ?></figcaption>
			<img src="/img/band/KivyXFIPYfM.jpg" alt="фото Алексея Скосырева">
		</figure>

		<figure>
			<figcaption><?= $this->translate('band.name.telegin'); ?><br/><?= $this->translate('band.name.telegin_desc'); ?></figcaption>
			<img src="/img/band/l3RfsyOkUtg.jpg" alt="фото Василия Телегина">
		</figure>
        <figure>
			<figcaption><?= $this->translate('band.name.julia'); ?><br/><?= $this->translate('band.name.julia_desc'); ?></figcaption>
			<img src="/img/band/9ybrmYSS580.jpg" alt="фото Юлии Усовой">
		</figure>
        <figure>
			<figcaption><?= $this->translate('band.name.lina'); ?><br/><?= $this->translate('band.name.julia_desc'); ?></figcaption>
			<img src="/img/band/BjrYB5NpIgw.jpg" alt="фото Лины Колесник">
		</figure>
        <figure>
			<figcaption><?= $this->translate('band.name.denis'); ?><br/><?= $this->translate('band.name.denis_desc'); ?></figcaption>
			<img src="/img/band/yPNCG2tbddc.jpg" alt="фото Дениса Никифорова">
		</figure>
	</div>
</section>
