<section class="field-bg">
	<h2 class="title-page-name text-center"><?= $this->translate('page.title.band'); ?></h2>

	<div class="band-photo">
		<figure>
			<figcaption>Юлия Усова</figcaption>
			<img src="/img/usova.jpg" alt="фото Юлии Усовой">
		</figure>
		<figure>
			<figcaption>Тимур Сигидин</figcaption>
			<img src="/img/timur.jpg" alt="фото Тимура Сигидина">
		</figure>
		<figure>
			<figcaption>Алексей Белкин</figcaption>
			<img src="/img/belkin.jpg" alt="фото Алексея Белкина">
		</figure>
		<figure>
			<figcaption>Пётр Сергеев</figcaption>
			<img src="/img/petja.jpg" alt="фото Петра Сергеева">
		</figure>
		<figure>
			<figcaption>Дмитрий Шихардин</figcaption>
			<img src="/img/shixard.jpg" alt="фото Дмитрия Шихардина">
		</figure>
		<figure>
			<figcaption>Алексей Скоссырев</figcaption>
			<img src="/img/skos.jpg" alt="фото Алексея Скоссырева">
		</figure>
	</div>
	<p>Группа «Отава ё» появилась на свет абсолютно спонтанно примерно в 2003 году, правда тогда мы еще не знали, что это будет самостоятельный коллектив:
	</p><p>
	Мы все были заняты в разных группах, и «Отава ё» стала своего рода реализацией того, что нам не удавалось делать в своих основных проектах.
	</p><p>
	Мы стараемся не быть очень серьезными, так что если вам покажется, что вы слышите что-то такое, чего никак не ожидали услышать, то это именно то, чего мы и добивались.
	</p>
	<p>Если вы хотите помочь артистам рублем — это можно сделать <a>тут</a>.</p>
</section>