<section class="field-bg">
	<h2 class="title-page-name text-center">Как с нами связаться</h2>

	<h3 class="title-contacts">Организация концертов</h3>
	<p>Алексей Белкин — otavae@gmail.com, + 7 921 637 87 68</p>

	<p class="titile-em">Booking in Scandinavia / Организация выступлений в Скандинавии:</p>
	<p>Jami Saarinen — jami@svm-agency.com, +35 845 114 35 30</p>
	<p><a rel="nofollow" target="_blank" href="www.svm-agency.com">www.svm-agency.com</a></p>

	<h3 class="title-contacts">Соц. сети</h3>
	<p><a rel="nofollow" target="_blank" href="http://myspace.com/otavae">http://myspace.com/otavae</a></p>
	<p><a rel="nofollow" target="_blank" href="http://otavae.kroogi.ru">http://otavae.kroogi.ru</a></p>
	<p><a rel="nofollow" target="_blank" href="http://vk.com/club662700">http://vk.com/club662700</a></p>
	<p><a rel="nofollow" target="_blank" href="http://www.youtube.com/user/ABelkin?feature=watch">www.youtube.com</a></p>

	<h3 class="title-contacts">Поддержка сайта</h3>
	<p>support@esemi.ru</p>

</section>