<section class="field-bg">
	<h2 class="title-page-name text-center"><?= $this->translate('page.title.contacts'); ?></h2>

	<h3 class="title-contacts"><?= $this->translate('сontacts.management'); ?></h3>
	<p>
		<?= $this->translate('band.name.rymanzev'); ?> —
		<a href="mailto:kupalaru@mail.ru" target="_blank" rel="nofollow">kupalaru@mail.ru</a>
	</p>

	<h3 class="title-contacts"><?= $this->translate('сontacts.organization'); ?></h3>
	<p class="title-em"><?= $this->translate('сontacts.booking.sng'); ?>:</p>
	<div class="forign-contact">
		<p><?= $this->translate('band.name.rymanzev'); ?> —
			<a href="mailto:kupalaru@mail.ru?Subject=Организация%20концерта" target="_blank" rel="nofollow">kupalaru@mail.ru</a>
			, +7 916 675 78 41
		</p>
	</div>
	<p class="title-em"><?= $this->translate('сontacts.booking.spb'); ?>:</p>
	<div class="forign-contact">
		<p><?= $this->translate('band.name.belkin'); ?> —
			<a href="mailto:otavae@gmail.com?Subject=Организация%20концерта" target="_blank" rel="nofollow">otavae@gmail.com</a>
			, + 7 921 637 87 68
		</p>
	</div>
	<p class="title-em"><?= $this->translate('сontacts.booking.usa'); ?>:</p>
	<div class="forign-contact">
		<p>Aysem Balay —
			<a href="mailto:aysem@charmenko.net?Subject=OtavaYo%20concert" target="_blank" rel="nofollow">aysem@charmenko.net</a>
			, CHARMWORKS
		</p>
		<p><a rel="nofollow" target="_blank" href="http://www.charmworks.net">www.charmworks.net</a></p>
	</div>

	<h3 class="title-contacts"><?= $this->translate('сontacts.links'); ?></h3>
	<p><a rel="nofollow" title="facebook.com" target="_blank" href="https://ru-ru.facebook.com/Otava-yo-%D0%9E%D1%82%D0%B0%D0%B2%D0%B0-%D1%91-210428005652269/">http://facebook.com</a></p>
	<p><a rel="nofollow" title="kroogi.ru" target="_blank" href="http://otavae.kroogi.ru">http://otavae.kroogi.ru</a></p>
	<p><a rel="nofollow" title="vk.com" target="_blank" href="http://vk.com/club662700">http://vk.com/club662700</a></p>
	<p><a rel="nofollow" title="youtube.com" target="_blank" href="http://www.youtube.com/user/ABelkin?feature=watch">http://youtube.com</a></p>

	<h3 class="title-contacts"><?= $this->translate('сontacts.support'); ?></h3>
	<p>
		<a href="mailto:support@esemi.ru?Subject=About%20OtavaYo" target="_blank" rel="nofollow">support@esemi.ru</a>
	</p>

</section>