<section class="field-bg">
	<p>
		Отава Ё - самая весёлая и самая популярная русская фолк-группа в мире, объездившая с гастролями более 25 стран и собирающая миллионы просмотров в YouTube, в этом году решила провести горячие предновогодние недели на родине! С 18 по 31 декабря у вас есть уникальная возможность увидеть искромётное шоу Отавы Ё на вашем праздничном мероприятии. Сделайте ваш праздник незабываемым!
	</p>

	<iframe width="560" height="315" src="https://www.youtube.com/embed/FWvrW9HJr2Q?rel=0" frameborder="0" allowfullscreen></iframe>
	<br>
	<iframe width="560" height="315" src="https://www.youtube.com/embed/JFAQGDjKM10?rel=0" frameborder="0" allowfullscreen></iframe>
	<br>
	<iframe width="560" height="315" src="https://www.youtube.com/embed/fPgoV_SptvU?rel=0" frameborder="0" allowfullscreen></iframe>

	тех. райдер (в приложении)
	бытовой райдер (в приложении)

	<p class="title-em">контакты:</p>
	<p><?= $this->translate('band.name.rymanzev'); ?> —
		<a href="mailto:kupalaru@mail.ru?Subject=Организация%20концерта" target="_blank" rel="nofollow">kupalaru@mail.ru</a>
		, +7 916 675 78 41
	</p>

</section>
