<section class="field-bg">
	<p>
		Отава Ё - самая весёлая и самая популярная русская фолк-группа в мире, объездившая с гастролями более 25 стран и собирающая миллионы просмотров в YouTube, в этом году решила провести горячие предновогодние недели на родине!
	</p>
	<p>
		С 18 по 31 декабря у вас есть уникальная возможность увидеть искромётное шоу Отавы Ё на вашем праздничном мероприятии. Сделайте ваш праздник незабываемым!
	</p>
	<br>
	<br>
	<div class="text-center">
		<iframe class="float_l" width="260" height="215" src="https://www.youtube.com/embed/FWvrW9HJr2Q?rel=0" frameborder="0" allowfullscreen></iframe>
		<iframe width="260" height="215" src="https://www.youtube.com/embed/JFAQGDjKM10?rel=0" frameborder="0" allowfullscreen></iframe>
		<iframe class="float_r" width="260" height="215" src="https://www.youtube.com/embed/fPgoV_SptvU?rel=0" frameborder="0" allowfullscreen></iframe>
	</div>

	<br>

	<p>
		<a href="http://otava-yo.spb.ru/media/Otava_Yo-tekhnicheskiy_rayder_2017.doc">Технический райдер</a>
	</p>
	<p>
		<a href="http://otava-yo.spb.ru/media/Otava_Yo_-_korotky_bytovoy_rayder_7.doc">Бытовой райдер</a>
	</p>
	
	<br>

	<h3 class="title">контакты:</h3>
	<p><?= $this->translate('band.name.rymanzev'); ?> —
		<a href="mailto:kupalaru@mail.ru?Subject=Организация%20концерта" target="_blank" rel="nofollow">kupalaru@mail.ru</a>
		, +7 916 675 78 41
	</p>

</section>
