<section class="field-bg">
	<h2 class="title-page-name text-center"><?= $this->translate('title.index.donate'); ?></h2>
	<iframe scrolling="no" src="https://money.yandex.ru/quickpay/shop-widget?writer=seller.." width="100%" height="250" frameborder="0" allowtransparency="true" scrolling="no"></iframe>
	<br>
	<p class="inline_blk title-em">For donate from outside of Russia:</p>
	<form class="inline_blk" action="https://paypal.me/AlexeyBelkin" target="_blank">
		<button type="submit">donate</button>
	</form>
</section>
