<section class="field-bg">
	<h2 class="title-page-name text-center"><?= $this->translate('title.index.donate'); ?></h2>
	<iframe class="center-margin" frameborder="0" allowtransparency="true" scrolling="no" src="https://money.yandex.ru/embed/donate.xml?account=410011983670239&quickpay=donate&payment-type-choice=on&default-sum=&targets=%D0%BC%D0%B0%D1%82%D0%B5%D1%80%D0%B8%D0%B0%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F+%D0%BF%D0%BE%D0%B4%D0%B4%D0%B5%D1%80%D0%B6%D0%BA%D0%B0+%D1%82%D0%B2%D0%BE%D1%80%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B3%D0%BE+%D0%BF%D0%BE%D1%82%D0%B5%D0%BD%D1%86%D0%B8%D0%B0%D0%BB%D0%B0+%D0%B3%D1%80%D1%83%D0%BF%D0%BF%D1%8B+&target-visibility=on&project-name=&project-site=&button-text=01" width="523" height="104"></iframe>
	<br/>
	<a href="https://paypal.me/AlexeyBelkin" target="_blank">For donate from outside of Russia</a>
</section>
