<section class="field-bg">
	<h2 class="title-page-name text-center"><?= $this->translate('title.index.donate'); ?></h2>
	<iframe src="https://money.yandex.ru/quickpay/shop-widget?writer=seller&targets=%D0%BF%D0%BE%D0%B4%D0%B4%D0%B5%D1%80%D0%B6%D0%B0%D1%82%D1%8C%20%D0%B3%D1%80%D1%83%D0%BF%D0%BF%D1%83%20%D0%9E%D1%82%D0%B0%D0%B2%D0%B0%20%D0%81%2F%20support%20Otava%20Yo%20&targets-hint=&default-sum=&button-text=11&hint=&successURL=&quickpay=shop&account=410011983670239" width="423" height="250" frameborder="0" allowtransparency="true" scrolling="no"></iframe>
	<br>
	<p class="inline_blk title-em">For donate from outside of Russia:</p>
	<form class="inline_blk" action="https://paypal.me/AlexeyBelkin" target="_blank">
		<button type="submit">donate</button>
	</form>
</section>
