<img src="img/foto.jpg" class="center-margin main-page-photo">
<section class="music">
	<? if( !is_null($this->audio) ): ?>
	<div class="music-name"><?= $this->escape($this->audio->title); ?></div>
	<img class="music-cover" src="img/cover_1.png">
	<audio controls class="music-player">
		<source src="<?= $this->escape($this->audio->media_link); ?>" type="audio/mp3">
	</audio>
	<? endif; ?>
</section>
<section class="nearrest-concert">
	<h2 class="title">Ближайщий концерт</h2>
	<? if( !is_null($this->concert) ): ?>
		<article class="nearrest-concert-info">
			<div class="nearrest-concert-date"><?= $this->prepareConcertDate($this->concert->date); ?></div>
			<h3 class="nearrest-concert-place"><?= $this->escape($this->concert->title); ?></h3>
			<p><?= $this->escape($this->concert->desc); ?></p>
		</article>
	<? endif; ?>
</section>