<img src="/img/foto.jpg" alt="Фото группы ОтаваЁ" class="center-margin main-page-photo">

<div class="right">
	<a href="<?= $this->url(array('id' => ( !is_null($this->concert) ) ? $this->concert->id : 0 ), 'staticConcertView', true) ?>">
		<section class="nearrest-concert">
			<div class="nearrest-concert-decor"></div>
			<? if( !is_null($this->concert) ): ?>
				<header>
					<time class="date nearrest-concert-date" datetime="<?= $this->prepareConcertDatetime($this->concert->date, $this->concert->time); ?>">
						<?= $this->prepareConcertDate($this->concert->date); ?>
					</time>
					<h2 class="nearrest-concert-title">Выступаем</h2>
				</header>
				<h3 class="nearrest-concert-place">
					<? if( !empty($this->concert->title) ): ?>
						<?= $this->escape($this->concert->title); ?>
					<? else: ?>
						<?= $this->escape($this->concert->place); ?>
					<? endif; ?>
				</h3>
			<? else: ?>
				<header>
					<time class="date nearrest-concert-date"></time>
				</header>
				<h3 class="title-em">
					<p>Концерты скоро будут</p>
				</h3>
			<? endif; ?>
		</section>
	</a>
	<section class="music">
		<p class="music-title">Кадриль</p>

		<div id="jquery_jplayer_index" class="jp-jplayer"></div>
		<div id="jp_container_1" class="jp-audio">
			<div class="jp-type-single">
				<div class="jp-gui jp-interface">
				<ul class="jp-controls">
					<li><a href="javascript:;" class="jp-play" tabindex="1"></a></li>
					<li><a href="javascript:;" class="jp-pause" tabindex="1"></a></li>
					<li><a href="javascript:;" class="jp-stop" tabindex="1">stop</a></li>
					<li><a href="javascript:;" class="jp-mute" tabindex="1" title="mute">mute</a></li>
					<li><a href="javascript:;" class="jp-unmute" tabindex="1" title="unmute">unmute</a></li>
					<li><a href="javascript:;" class="jp-volume-max" tabindex="1" title="max volume">max volume</a></li>
				</ul>
				<div class="jp-progress">
					<div class="jp-seek-bar">
						<div class="jp-play-bar"></div>
					</div>
				</div>
				<div class="jp-volume-bar">
					<div class="jp-volume-bar-value"></div>
				</div>
					<div class="jp-time-holder">
						<div class="jp-current-time"></div>
						<div class="jp-duration"></div>
						<ul class="jp-toggles">
							<li><a href="javascript:;" class="jp-repeat" tabindex="1" title="repeat">repeat</a></li>
							<li><a href="javascript:;" class="jp-repeat-off" tabindex="1" title="repeat off">repeat off</a></li>
						</ul>
					</div>
				</div>
				<div class="jp-title">
					<ul>
						<li>Bubble</li>
					</ul>
				</div>
				<div class="jp-no-solution">
					<h5>Update Required</h5>
					To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
				</div>
			</div>
		</div>
	</section>
</div>

<a href="<?= $this->url(array('id' => $this->news->id ), 'staticNewsView', true) ?>">
	<section class="last-news">
		<div class="last-news-decor"></div>
			<header>
				<time class="date last-news-date" datetime="<?= $this->escape($this->news->date_publish); ?>">
					<?= $this->prepareConcertDate($this->news->date_publish); ?>
				</time>
				<h2 class="title-bigger">Последние новости</h2>
			</header>
			<p><?= $this->escape($this->news->content); ?></p>
	</section>
</a>

