ALTER TABLE `album`
ADD `link_ozone` VARCHAR( 255 ) NULL DEFAULT NULL ,
ADD `link_itunes` VARCHAR( 255 ) NULL DEFAULT NULL ,
ADD `link_bandcamp` VARCHAR( 255 ) NULL DEFAULT NULL ,
ADD `link_googleplay` VARCHAR( 255 ) NULL DEFAULT NULL,
ADD `link_navi` VARCHAR( 255 ) NULL DEFAULT NULL,
ADD `link_amazon` VARCHAR( 255 ) NULL DEFAULT NULL,
ADD `link_yandex` VARCHAR( 255 ) NULL DEFAULT NULL;