<?php

$authFlag = Zend_Controller_Action_HelperBroker::getStaticHelper('CheckAccess')->moderAccess();

?>

<section class="field-bg">
	<h2 class="title-page-name text-center"><?= $this->translate('title.video.index'); ?></h2>

	<?php if( $authFlag ): ?>
		<a title="добавить видео" class="news-button" href="<?= $this->url(array(), 'staticVideoCreate') ?>"><?= $this->translate('button.add'); ?></a>
	<?php endif; ?>

	<?php foreach( $this->video as $item ): ?>
		<article class="video-block">
			<header>
				<h3 class="title-em video-title">
					<?= $this->escape($item->desc); ?>
				</h3>
			</header>
			<div class="video">
				<?= $item->player_code; ?>
			</div>
			<footer>
				<?php if( $authFlag ): ?>
					<a class="edit" title="редактировать" href="<?= $this->url(array('idV' => $item->id ), 'staticVideoEdit') ?>"><?= $this->translate('button.edit'); ?></a>
					<a class="delete" title="удалить" href="<?= $this->url(array('idV' => $item->id ), 'staticVideoDelete') ?>"><?= $this->translate('button.delete'); ?></a>
				<?php endif; ?>
			</footer>
		</article>
	<hr>
	<?php endforeach; ?>
</section>