<section class="field-bg">
	<h2 class="title-page-name text-center">Гостевая книга</h2>
	<div class="js-guestbook-add-button guest-button  <?= ( $this->showForm ) ? 'hide' : ''; ?>">Написать</div>
	<section class="js-guestbook-add-form guest-form <?= ( !$this->showForm ) ? 'hide' : ''; ?>">
		<?= $this->partial('Partials/guestbook-new-post.phtml', array(
			'postData' => $this->postData,
			'error' => $this->errorMessage,
			'recaptcha' => $this->recaptcha)); ?>
	</section>
	<hr>

	<? foreach( $this->notes as $item ): ?>
		<article class="guest-post">
			<header>
				<span class="name title-em"><?= $this->escape($item->author); ?></span>
				<? if( !empty($item->city) ): ?>
					<span class="city">(<?= $this->escape($item->city); ?>)</span>
				<? endif; ?>
				<? if( !empty($item->email) ): ?>
					<a class="email" href="mailto:<?= $this->escape($item->email); ?>" target="_blank" rel="nofollow">почта</a>
				<? endif; ?>
				<? if( !empty($item->site) ): ?>
					<a class="site" href="<?= $this->escape($item->site); ?>" target="_blank" rel="nofollow">сайт</a>
				<? endif; ?>
				<time datetime="<?= $this->escape($item->iso_date); ?>"><?= $this->escape($item->user_date); ?></time>
			</header>
			<p>
				<?= $this->escape($item->content); ?>
			</p>
		</article>
		<hr>
	<? endforeach; ?>

</section>