<section class="field-bg">
	<h2 class="title-page-name text-center">Гостевая книга</h2>
	<p class="js-guestbook-add-button">@TODO BUTTON</p>
	<div class="js-guestbook-add-form  <?= (empty($this->postData)) ? 'hide' : ''; ?>">
		<? if( !empty($this->errorMessage) ): ?>
			<div><?= $this->escape($this->errorMessage); ?></div>
		<? endif; ?>
		<?= $this->partial('Partials/guestbook-new-post.phtml', array('postData' => $this->postData,'recaptcha' => $this->recaptcha)); ?>
	</div>

	<? foreach( $this->notes as $item ): ?>
		<article class="guest-post">
		<header>
			<span class="name title-em"><?= $this->escape($item->author); ?></span>
			<? if( !empty($item->city) ): ?>
				<span class="city">(<?= $this->escape($item->city); ?>)</span>
			<? endif; ?>
			<? if( !empty($item->email) ): ?>
				<a class="email" href="mailto:<?= $this->escape($item->email); ?>" target="_blank" rel="nofollow">почта</a>
			<? endif; ?>
			<? if( !empty($item->site) ): ?>
				<a class="site" href="<?= $this->escape($item->site); ?>" target="_blank" rel="nofollow">сайт</a>
			<? endif; ?>
			<time><?= $this->escape($item->date_publish); ?></time>
		</header>
		<p>
			<?= $this->escape($item->content); ?>
		</p>
		</article>
		<hr>
	<? endforeach; ?>

</section>