<section class="field-bg">
	<p>
		<?=(isset($this->errorMessage)) ? $this->escape($this->errorMessage) : ''; ?>
	</p>
	<form name="login-form" method="POST" class="login-form">
		<label for="login" class="auth-login"> Логин: </label>
		<input type="text" id="login" name="login" class="login" value="<?= (isset($this->login)) ? $this->escape($this->login) : ''; ?>" placeholder="логин" maxlength="50"/>
		<br>
		<label for="pass"> Пароль: </label>
		<input type="password" id="pass" name="pass" placeholder="пароль" class="pass"/>
		<input type="submit" name="войти" value="войти" class="submit">
		<div>
			<?= $this->recaptcha->getHTML(); ?>
		</div>
	</form>
</section>