<div>
	<?=(isset($this->errorMessage)) ? $this->escape($this->errorMessage) : ''; ?>
</div>
<form name="login-form" method="POST">
	<input type="text" name="login" value="<?= (isset($this->login)) ? $this->escape($this->login) : ''; ?>" placeholder="логин" maxlength="50"/>
	<input type="password" name="pass" placeholder="пароль"/>
	<input type="submit" name="войти" value="войти">
	<div>
		<?= $this->recaptcha->getHTML(); ?>
	</div>
</form>