<section class="field-bg">
	<h2 class="title-page-name text-center">новости</h2>
	<?
	$currentYear = date('Y');
	foreach( $this->news as $item ):
		$itemYear = DateTime::createFromFormat('Y-m-d', $item->date_publish)->format('Y');
		if( $itemYear != $currentYear )
		{
			printf('<h3 class="old-concert-headding text-center">%s</h3>', $this->escape($itemYear));
			$currentYear = $itemYear;
		}
	?>
		<article class="news-block">
			<header>
				<time class="date-news" datetime="<?= $this->escape($item->date_publish); ?>">
					<?= $this->prepareConcertDate($item->date_publish); ?>
				</time>
				<h3 class="title">
					<a name="<?= sprintf("view%d", $item->id); ?>" href="<?php echo $this->url(array('id' => $item->id ), 'staticNewsView', true) ?>">
						<?= $this->escape($item->title); ?>
					</a>
				</h3>
			</header>
			<?= $item->content; ?>
			<footer>
				<p class="signature"><?= $this->escape($this->moder_author); ?></p>
			</footer>
		</article>
		<hr>
	<? endforeach; ?>
</section>