<section class="field-bg">
	<h2 class="title-page-name text-center">ближайшие концерты</h2>
	<? foreach( $this->concerts as $item ): ?>
		<article class="concert-block">
			<header>
				<time class="date-bigger date-concert">
					<?= $this->prepareConcertDate($item->date); ?>
					<div class="time">
						<?= ( !empty($item->time) ) ? $this->escape($item->time) : ''; ?>
					</div>
				</time>

				<hgroup>
					<h3 class="concert-name">
						<a class="title" name="<?= sprintf("view%d", $item->id); ?>" href="<?php echo $this->url(array('id' => $item->id ), 'staticConcertView', true) ?>">
							<?= $this->escape($item->title); ?>
						</a>
					</h3>

					<? if( !empty($item->place) ): ?>
						<h4 class="concert-place"><?= $this->escape($item->place); ?></h4>
					<? endif; ?>
				</hgroup>
			</header>

			<p>
				<?= $this->escape($item->desc); ?>
			</p>
			<? if( !empty($item->link) ): ?>
				<p class="concert-link">
					<a rel="nofollow" target="_blank" href="<?= $item->link ?>" rel="nofollow"><?= $this->escape($item->link); ?></a>
				</p>
			<? endif; ?>
			<? if( !empty($item->cost) ): ?>
				<p class="concert-ticets">Билеты: <?= $this->escape($item->cost); ?>р.</p>
			<? endif; ?>
		</article>
		<hr>
	<? endforeach; ?>
	<section>
		<h2 class="old-concert-headding text-center">прошедшие концерты</h2>
		<? foreach( $this->oldConcerts as $item ): ?>
			<article class="concert-block">
				<header>
					<time class="date-bigger date-concert">
						<?= $this->prepareConcertDate($item->date); ?>
						<div class="time">
							<?= ( !empty($item->time) ) ? $this->escape($item->time) : ''; ?>
						</div>
					</time>

					<hgroup>
						<h3 class="concert-name">
							<a class="title" name="<?= sprintf("view%d", $item->id); ?>" href="<?php echo $this->url(array('id' => $item->id ), 'staticConcertView', true) ?>">
								<?= $this->escape($item->title); ?>
							</a>
						</h3>

						<? if( !empty($item->place) ): ?>
							<h4 class="concert-place"><?= $this->escape($item->place); ?></h4>
						<? endif; ?>
					</hgroup>
				</header>
				<p><?= $this->escape($item->desc); ?></p>
				<? if( !empty($item->link) ): ?>
					<p class="concert-link">
						<a rel="nofollow" target="_blank" href="<?= $item->link ?>" rel="nofollow"><?= $this->escape($item->link); ?></a>
					</p>
				<? endif; ?>
				<? if( !empty($item->cost) ): ?>
					<p class="concert-ticets">Билеты: <?= $this->escape($item->cost); ?>р.</p>
				<? endif; ?>
			</article>
			<hr>
		<? endforeach; ?>
	</section>
</section>