<div class="field-bg">
	<h2 class="title text-center">ближайшие концерты</h2>
	<? foreach( $this->concerts as $item ): ?>
		<article>
			<header>
				<h3 class="title"><?= $this->escape($item->title); ?></h3>
				<? if( !empty($item->place) ): ?>
					<p><?= $this->escape($item->place); ?></p>
				<? endif; ?>
				<date class="date">
					<?= $this->prepareConcertDate($item->date); ?>
					<?= ( !empty($item->time) ) ? $this->escape($item->time) : ''; ?>
				</date>
			</header>
			<p><?= $this->escape($item->desc); ?></p>
			<? if( !empty($item->link) ): ?>
				<p><a href="<?= $item->link ?>" rel="nofollow">подробнее</a></p>
			<? endif; ?>
			<? if( !empty($item->cost) ): ?>
				<p>Билеты от <?= $this->escape($item->cost); ?>р.</p>
			<? endif; ?>
		</article>
	<? endforeach; ?>
</div>
<div class="field-bg">
	<h2 class="title text-center">прошедшие концерты</h2>
	<? foreach( $this->oldConcerts as $item ): ?>
		<article>
			<header>
				<h3 class="title"><?= $this->escape($item->title); ?></h3>
				<? if( !empty($item->place) ): ?>
					<p><?= $this->escape($item->place); ?></p>
				<? endif; ?>
				<date class="date">
					<?= $this->prepareConcertDate($item->date); ?>
					<?= ( !empty($item->time) ) ? $this->escape($item->time) : ''; ?>
				</date>
			</header>
			<p><?= $this->escape($item->desc); ?></p>
			<? if( !empty($item->link) ): ?>
				<p><a href="<?= $item->link ?>" rel="nofollow">подробнее</a></p>
			<? endif; ?>
			<? if( !empty($item->cost) ): ?>
				<p>Билеты от <?= $this->escape($item->cost); ?>р.</p>
			<? endif; ?>
		</article>
	<? endforeach; ?>
</div>
