<?php

$version = $this->cacheVersion();

$this->headLink()->appendStylesheet("/css/jquery-ui-1.10.3.custom.min.css?{$version}");
$this->headScript()->appendFile( "/js/jquery-ui-1.10.3.custom.min.js");

$authFlag = Zend_Controller_Action_HelperBroker::getStaticHelper('CheckAccess')->moderAccess();

?>

<section class="field-bg">
	<h2 class="title-page-name text-center"><?= $this->translate('title.audio.index'); ?></h2>

	<p class="error-fixed js-ajax-error">
		<?php if( !empty($this->error) ): ?>
			<?= $this->escape($this->error); ?>
		<?php endif; ?>
	</p>

	<?php if( $authFlag ): ?>
		<a class="news-button" href="<?= $this->url(array(), 'staticAlbumCreate') ?>"><?= $this->translate('button.album.add'); ?></a>
	<?php endif; ?>

	<?php foreach($this->albums as $album): ?>
		<article>
			<hgroup>
				<h3 class="title-album"><?= $this->escape($album['title']); ?></h3>
				<time class="album-year" datetime="<?= $this->escape($album['year']); ?>"><?= $this->escape($album['year']); ?></time>
			</hgroup>

			<div class="album-cover">
				<img alt="обложка альбома «<?= $this->escape($album['title']); ?>»" src="<?= $album['img_link']; ?>">
			</div>
			<?php if( $authFlag ): ?>
				<ul class="js-playlist-editable"
					data-album-id="<?= $this->escape($album['id']); ?>"
					data-remove-url="<?= $this->url(array(), 'audioRemoveTrack'); ?>"
					data-sort-url="<?= $this->url(array(), 'audioSortPlaylist'); ?>"
					data-add-url="<?= $this->url(array(), 'audioAddTrack'); ?>">
			<?php else: ?>
				<ul class="audio-list">
			<?php endif; ?>
			<?php foreach($this->audio as $audio): ?>
				<?php
					if( $album['id'] == $audio['album_id'] ){
						echo $this->partial('Partials/audio-item.phtml', array(
							'audio' => $audio,
							'authFlag' => $authFlag));
					}
				?>
			<?php endforeach; ?>
			</ul>

			<?php if( $authFlag ): ?>
				<div class="adding-new-track">
					<label for="track-name"><?= $this->translate('label.new.track'); ?>:</label>
					<div class="hide js-playlist-item-template">
						<?= $this->partial('Partials/audio-item.phtml', array(
							'audio' => array('audio_link' => null, 'id' => 'REPLACE_ID', 'title' => 'REPLACE_TITLE'),
							'authFlag' => $authFlag)); ?>
					</div>
					<input type="text" id="track-name" value="" placeholder="Введите название трека" class="js-playlist-add-title input-song-name">
					<span class="js-playlist-add-button" data-mode="add"><?= $this->translate('button.add.lowercase'); ?></span>
				</div>
			<?php endif; ?>

			<?php if( !empty($album['desc']) ): ?>
				<div class="album-desc"><?= $album['desc']; ?></div>
			<?php endif; ?>

			<?php if( $authFlag ): ?>
				<footer>
					<a class="edit" title="редактировать" href="<?= $this->url(array('idAl' => $album['id'] ), 'staticAlbumEdit') ?>"><?= $this->translate('button.edit'); ?></a>
					<a class="delete" title="удалить" href="<?= $this->url(array('idAl' => $album['id'] ), 'staticAlbumDelete') ?>"><?= $this->translate('button.delete'); ?></a>
				</footer>
			<?php endif; ?>

			<nav>
				<?php if (!empty($album['link_ozone'])): ?>
					<a class="album-buy-button" href='<?= $this->escape($album['link_ozone']); ?>' target='_blank'>
						<img alt="купить на ozone" src="/img/musicSources/button_ozon.jpg">
					</a>
				<?php endif; ?>
				<?php if (!empty($album['link_itunes'])): ?>
					<a class="album-buy-button" href='<?= $this->escape($album['link_itunes']); ?>' target='_blank'>
						<img alt="купить на iTunes" src="/img/musicSources/Download_on_iTunes_Badge_RU_110x40_0730.jpg">
					</a>
				<?php endif; ?>
				<?php if (!empty($album['link_bandcamp'])): ?>
					<a class="album-buy-button" href='<?= $this->escape($album['link_bandcamp']); ?>' target='_blank'>
						<img alt="купить на bandcamp" src="/img/musicSources/BandCamp-Button-110x40.png">
					</a>
				<?php endif; ?>
				<?php if (!empty($album['link_googleplay'])): ?>
					<a class="album-buy-button" href='<?= $this->escape($album['link_googleplay']); ?>' target='_blank'>
						<img alt="купить на googleplay" src="/img/musicSources/google_play_button_110x40.jpg">
					</a>
				<?php endif; ?>
				<?php if (!empty($album['link_navi'])): ?>
					<a class="album-buy-button" href='<?= $this->escape($album['link_navi']); ?>' target='_blank'>
						<img alt="купить на navi" src="/img/musicSources/NaviMusic-110x40-Download.png">
					</a>
				<?php endif; ?>
				<?php if (!empty($album['link_amazon'])): ?>
					<a class="album-buy-button" href='<?= $this->escape($album['link_amazon']); ?>' target='_blank'>
						<img alt="купить на amazon" src="/img/musicSources/Amazon-Button-110x40.png">
					</a>
				<?php endif; ?>
				<?php if (!empty($album['link_yandex'])): ?>
					<a class="album-buy-button" href='<?= $this->escape($album['link_yandex']); ?>' target='_blank'>
						<img alt="послушать и купить на yandex music" src="/img/musicSources/40x160_yandex.music_badge.png">
					</a>
				<?php endif; ?>
			</nav>
		</article>
		<hr>
	<?php endforeach; ?>


	<div class="player">
		<div id="jquery_jplayer_audio" class="jp-jplayer"></div>
		<div id="jp_container_1" class="jp-audio">
			<div class="jp-type-single">
				<div class="jp-gui jp-interface">
				<ul class="jp-controls">
					<li><a href="javascript:;" class="jp-play" tabindex="1">play</a></li>
					<li><a href="javascript:;" class="jp-pause" tabindex="1">pause</a></li>
					<li><a href="javascript:;" class="jp-stop" tabindex="1">stop</a></li>
					<li><a href="javascript:;" class="jp-mute" tabindex="1" title="mute">mute</a></li>
					<li><a href="javascript:;" class="jp-unmute" tabindex="1" title="unmute">unmute</a></li>
					<li><a href="javascript:;" class="jp-volume-max" tabindex="1" title="max volume">max volume</a></li>
				</ul>
				<div class="jp-progress">
					<div class="jp-seek-bar">
						<div class="jp-play-bar"></div>
					</div>
				</div>
				<div class="jp-volume-bar">
					<div class="jp-volume-bar-value"></div>
				</div>
					<div class="jp-time-holder">
						<div class="jp-current-time"></div>
						<div class="jp-duration"></div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<input type="hidden" name="csrf" value="<?= $this->csrfToken(); ?>">
</section>
