<?
$version = $this->cacheVersion();

$this->headLink()->appendStylesheet("/css/jquery-ui-1.10.3.custom.min.css?{$version}");
$this->headScript()->appendFile( "/js/jquery-ui-1.10.3.custom.min.js");

?>


<section class="field-bg">
	<h2 class="title-page-name text-center"><?= $this->translate('title.audio.playlist-edit'); ?></h2>
	<p class="error js-ajax-error">
		<? if( !empty($this->error) ): ?>
			<?= $this->escape($this->error); ?>
		<? endif; ?>
	</p>

	<div>
		<h3><?= $this->escape($this->albumData['title']); ?></h3>

		<div>
			<style>
				.js-playlist-editable { list-style-type: none; margin: 0; padding: 0; width: 60%; }
				.js-playlist-editable li { margin: 0 5px 5px 5px; padding: 5px; font-size: 1.2em; height: 1.5em; }
				html>body .js-playlist-editable li { height: 1.5em; line-height: 1.2em; }
				.ui-state-highlight { height: 1.5em; line-height: 1.2em; }
			</style>
			<ul class="js-playlist-editable"
				data-album-id="<?= $this->escape($this->albumData['id']); ?>"
				data-remove-url="<?= $this->url(array(), 'audioRemoveTrack'); ?>"
				data-edit-url="<?= $this->url(array(), 'audioEditTrack'); ?>"
				data-sort-url="<?= $this->url(array(), 'audioSortPlaylist'); ?>"
				data-add-url="<?= $this->url(array(), 'audioAddTrack'); ?>">
			<? foreach( $this->playlistData as $track ): ?>
				<li data-id="<?= $this->escape($track->id); ?>">
					<span class="js-playlist-order-button">ползунок</span>
					<input type="text" value="<?= $this->escape($track->title); ?>" disabled="disabled"/>
					<span class="js-playlist-edit-button hide" data-mode="edit">edit</span>
					<span class="js-playlist-remove-button hide">del</span>
				</li>
			<? endforeach; ?>
			</ul>
			<br/>
		</div>


		<div>
			добавка нового<br/>
			<div class="hide js-playlist-item-template">
				<li data-id="">
					<span class="js-playlist-order-button">ползунок</span>
					<input type="text" value="" disabled="disabled"/>
					<span class="js-playlist-edit-button hide" data-mode="edit">edit</span>
					<span class="js-playlist-remove-button hide">del</span>
				</li>
			</div>
			<input type="text" value="" placeholder="Введите название трека" class="js-playlist-add-title">
			<span class="js-playlist-add-button" data-mode="add">add</span>
		</div>
	</div>

	<input type="hidden" name="csrf" value="<?= $this->csrfToken(); ?>">
</section>