<section class="field-bg">
	<h2 class="title-page-name text-center"><?= $this->translate('title.audio.track-edit'); ?></h2>

	<? if( !empty($this->errorMessage) ): ?>
		<p class="error"><?= $this->errorMessage; ?></p>
	<? endif; ?>

	<form enctype="multipart/form-data" name="audiofile-form" method="POST" class="audiofile-form">
		<div>
			<label for="track-name"><?= $this->translate('label.song.name'); ?>:</label>
			<input class="input-song-name" id="track-name"
				type="text"
				name="title"
				value="<?= (isset($this->trackData['title'])) ? $this->escape($this->trackData['title']) : ''; ?>"
				placeholder="Введите название трека"
				maxlength="255"><br>
			<label for="audiofile_src"><?= $this->translate('label.new.audiofile'); ?>:</label>
			<input name="audiofile_src" id="audiofile_src" type="file"/>
			<input type="hidden" name="MAX_FILE_SIZE" value="30000000" />
			<p class="warning"><?= $this->translate('other.track.format.warning'); ?></p>
		</div>

		<input type="hidden" name="csrf" value="<?= $this->csrfToken(); ?>">
		<input class="submit" type="submit" name="отправить" value="<?= $this->translate('button.submit'); ?>">
	</form>

</section>