<?php
$version = $this->cacheVersion();

$this->headLink()->appendStylesheet("/css/jquery-ui-1.10.3.custom.min.css?{$version}");

$this->headScript()->appendFile( "/js/jquery-ui-1.10.3.custom.min.js");
$this->headScript()->appendFile( "/js/ckeditor/ckeditor.js");
$this->headScript()->appendFile( "/js/ckeditor/adapters/jquery.js");

?>

<?php if( !empty($this->error) ): ?>
	<p class="error"><?= $this->error; ?></p>
<?php endif; ?>

<form enctype="multipart/form-data" name="album-form" method="POST" class="album-form">
	<table>
		<tbody>
			<tr>
				<td>
					<label for="title">Название: </label>
				</td>
				<td>
					<input type="text" name="title" id="title" value="<?= (isset($this->albumData['title'])) ? $this->escape($this->albumData['title']) : ''; ?>" placeholder="Название" maxlength="255"/>
				</td>
			</tr>
			<tr>
				<td>
					<label for="year">Год: </label>
				</td>
				<td>
					<input type="number" name="year" id="year" value="<?= (isset($this->albumData['year'])) ? $this->escape($this->albumData['year']) : ''; ?>" placeholder="Год yyyy" maxlength="4"/>
				</td>
			</tr>
		</tbody>
	</table>
	<div>
		<label for="album_image">Обложка альбома:</label>
		<input name="album_image" id="album_image" type="file"  class="adding-album-image"/>
		<?php if( !empty($this->albumData['img_link']) ): ?>
			<img alt="album cover" title="album cover" src="<?= $this->albumData['img_link']; ?>"/>
		<?php endif; ?>
		<input type="hidden" name="MAX_FILE_SIZE" value="2000000" />
			<p>максимальный размер 2MB, автоматически масштабируется до 222x200 px</p>
	</div>

	<label for="desc" class="desc">Описание: </label><br>
	<textarea class="js-editor-album message" name="desc" id="desc" placeholder="Описание"><?= (isset($this->albumData['desc'])) ? $this->albumData['desc'] : ''; ?></textarea><br>

	Order links<br/>
	ozone <input name='link_ozone' type='url' value="<?= (isset($this->albumData['link_ozone'])) ? $this->escape($this->albumData['link_ozone']) : ''; ?>" maxlength="255"><br/>
	iTunes <input name='link_itunes' type='url' value="<?= (isset($this->albumData['link_itunes'])) ? $this->escape($this->albumData['link_itunes']) : ''; ?>" maxlength="255"><br/>
	BandCamp <input name='link_bandcamp' type='url' value="<?= (isset($this->albumData['link_bandcamp'])) ? $this->escape($this->albumData['link_bandcamp']) : ''; ?>" maxlength="255"><br/>
	Google Play <input name='link_googleplay' type='url' value="<?= (isset($this->albumData['link_googleplay'])) ? $this->escape($this->albumData['link_googleplay']) : ''; ?>" maxlength="255"><br/>
	Navi <input name='link_navi' type='url' value="<?= (isset($this->albumData['link_navi'])) ? $this->escape($this->albumData['link_navi']) : ''; ?>" maxlength="255"><br/>
	Amazon <input name='link_amazon' type='url' value="<?= (isset($this->albumData['link_amazon'])) ? $this->escape($this->albumData['link_amazon']) : ''; ?>" maxlength="255"><br/>
	Yandex <input name='link_yandex' type='url' value="<?= (isset($this->albumData['link_yandex'])) ? $this->escape($this->albumData['link_yandex']) : ''; ?>" maxlength="255"><br/>

	<input type="hidden" name="csrf" value="<?= $this->csrfToken(); ?>">
	<input class="submit" type="submit" name="отправить" value="отправить">
</form>