<li
	class="<?php if( !is_null($this->audio['audio_link']) ) echo 'js-track'; ?>"
	track-id="<?= $this->audio['id'] ?>"
	media-link="<?= $this->escape($this->audio['audio_link']) ?>">
<?php if( !is_null($this->audio['audio_link']) ): ?>
	<div class="js-audio-item-play play"></div>
	<div class="js-audio-item-stop stop hide"></div>
<?php endif; ?>

<?= $this->escape($this->audio['title']) ?>

<?php if( $this->authFlag ): ?>
	<span class="delete-track js-playlist-remove-button"></span>
	<a class="edit-track" href="<?= $this->url(array('idT' => $this->audio['id']), 'staticTrackEdit'); ?>"></a>
<?php endif; ?>

</li>