<? if( !empty($this->error) ): ?>
	<p class="error"><?= $this->error; ?></p>
<? endif; ?>

<form name="concert-form" method="POST" class="concert-form">
	<table>
		<tbody>
			<tr>
				<td>
					<label for="title">Заголовок: </label>
				</td>
				<td>
					<input type="text" name="title" id="title" value="<?= (isset($this->concertData['title'])) ? $this->escape($this->concertData['title']) : ''; ?>" placeholder="Заголовок" maxlength="1024"/>
				</td>
			</tr>
			<tr>
				<td>
					<label for="place">Место: </label>
				</td>
				<td>
					<input type="text" name="place" id="place" value="<?= (isset($this->concertData['place'])) ? $this->escape($this->concertData['place']) : ''; ?>" placeholder="Место" maxlength="1024"/>
				</td>
			</tr>
			<tr>
				<td>
					<label for="link">Ссылка: </label>
				</td>
				<td>
					<input type="text" name="link" id="link" value="<?= (isset($this->concertData['link'])) ? $this->escape($this->concertData['link']) : ''; ?>" placeholder="Ссылка" maxlength="1024"/>
				</td>
			</tr>
			<tr>
				<td>
					<label for="cost">Стоимость: </label>
				</td>
				<td>
					<input type="text" name="cost" id="cost" value="<?= (isset($this->concertData['cost'])) ? $this->escape($this->concertData['cost']) : ''; ?>" placeholder="Цена билетов" maxlength="100"/>
				</td>
			</tr>
			<tr>
				<td>
					<label for="date">Дата: </label>
				</td>
				<td>
					<input type="date" name="date" id="date" value="<?= (isset($this->concertData['date'])) ? $this->escape($this->concertData['date']) : ''; ?>" placeholder="Дата dd.mm.yy" maxlength="10"/>
				</td>
			</tr>
			<tr>
				<td>
					<label for="time">Время: </label>
				</td>
				<td>
					<input type="time" name="time" id="time" value="<?= (isset($this->concertData['time'])) ? $this->escape($this->concertData['time']) : ''; ?>" placeholder="Время hh:mm" maxlength="5"/>
				</td>
			</tr>
		</tbody>
	</table>
	<label for="desc">Описание: </label><br>
	<textarea class="message" name="desc" id="desc" placeholder="Описание"><?= (isset($this->concertData['desc'])) ? $this->escape($this->concertData['desc']) : ''; ?></textarea><br>

	<input class="submit" type="submit" name="отправить" value="отправить">
</form>