<? if( !empty($this->error) ): ?>
	<p class="error"><?= $this->error; ?></p>
<? endif; ?>

<form name="post" method="POST" class="video-form">
	<input type="hidden" name="csrf" value="<?= $this->csrfToken(); ?>">
	<label for="desc"><?= $this->translate('label.title'); ?>: </label>
	<input type="text" name="desc" id="desc" value="<?= (isset($this->videoData['desc'])) ? $this->escape($this->videoData['desc']) : ''; ?>" placeholder="<?= $this->translate('placeholder.video.desc'); ?>" maxlength="1024"/><br>
	<textarea class="message" name="player_code" placeholder="<?= $this->translate('placeholder.video.code'); ?>"><?= (isset($this->videoData['player_code'])) ? $this->escape($this->videoData['player_code']) : ''; ?></textarea><br>
	<input class="submit" type="submit" name="отправить" value="<?= $this->translate('button.submit'); ?>">
</form>