	<h2 class="small-title mrg-left-13 mrg-top-21">
	<?= $this->message ?>
	</h2>

	<?php if (isset($this->exceptionMessage)): ?>
	<p class="mrg-left-21">
	<?= $this->exceptionMessage ?>
	</p>
	<?php endif ?>


	<?php if (isset($this->exception)): ?>
	<h3 class="subtitle mrg-left-13">Exception information:</h3>
	<p class="mrg-left-21">
	<strong class="bold">Message:</strong>
	<?= $this->exception->getMessage() ?>
	</p>
	<h3 class="subtitle mrg-left-13">Stack trace:</h3>
	<pre><?= $this->exception->getTraceAsString() ?>
	</pre>
		<h3>Request Parameters:</h3>
	<pre><?= var_export($this->request->getParams(), true) ?>
	</pre>
		<?php endif ?>
