<section class="field-bg">
	<h2 class="title-page-name text-center">
		<?= $this->message ?>
	</h2>

		<?php if (isset($this->exceptionMessage)): ?>
		<p>
		<?= $this->exceptionMessage ?>
		</p>
		<?php endif ?>


		<?php if (isset($this->exception)): ?>
		<h3 class="title-error">Exception information:</h3>
		<p>
		<strong class="bold">Message:</strong>
		<?= $this->exception->getMessage() ?>
		</p>
		<h3 class="title-error">Stack trace:</h3>
		<pre><?= $this->exception->getTraceAsString() ?>
		</pre>
			<h3 class="title-error">Request Parameters:</h3>
		<pre><?= var_export($this->request->getParams(), true) ?>
		</pre>
			<?php endif ?>
</section>