<?php

$this->headMeta()
		->setHttpEquiv('Content-Language', 'ru-RU')
		->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');

$version = $this->cacheVersion();

$this->headScript()->prependFile( "/js/main.js?{$version}");
$this->headLink()->prependStylesheet("/css/main.css?{$version}");

$this->headTitle('Отава Ё');
$this->headTitle()->setSeparator(' / ');


echo $this->doctype();
?>
<html>
	<head>
		<?php echo $this->headMeta(); ?>
		<?php echo $this->headTitle(); ?>
		<?php echo $this->render('counters.phtml'); ?>
		<link rel="icon" href="/img/favicon.ico" type="image/x-icon"/>
		<link rel="shortcut icon" href="/img/favicon.ico" type="image/x-icon"/>
		<link rel="author" href="/humans.txt" />
                <link href='http://fonts.googleapis.com/css?family=Ruslan+Display&subset=latin,cyrillic-ext' rel='stylesheet' type='text/css'>
		<?php echo $this->headLink(); ?>
	</head>
	<body>
            <div class="wrapper">
                <header class="header" >
                    <img src="img/otava_logo_main.png" class="logo">
                    <div class="out-links-block">
                        <div class="out-links">1</div>
                        <div class="out-links">2</div>
                        <div class="out-links">3</div>
                        <div class="out-links">4</div>
                    </div>
                </header>
                <nav class="menu-block">
                     <ul class="menu-links">
                        <li><a href="<?php echo $this->url(array(), 'staticIndex', true) ?>">главная</a></li>
                        <li>новости</li>
                        <li>концерты</li>
                        <li><a href="<?php echo $this->url(array(), 'staticBand', true) ?>">о группе</a></li>
                        <li>аудио</li>
                        <li>видео</li>
                        <li>гостевая</li>
                        <li><a href="<?php echo $this->url(array(), 'staticContacts', true) ?>">контакты</a></li>
                    </ul>
                </nav>

               <div class="content">
                    <?php echo $this->layout()->content; ?>
                </div>	
                <div class="push"></div>    
            </div>
            
            <footer class="footer">
                    копирайты итд
            </footer>

            <?php echo $this->headScript(); ?>
	</body>
</html>