<?php

$this->headMeta()
		->setHttpEquiv('Content-Language', 'ru-RU')
		->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');

$version = $this->cacheVersion();

$this->headScript()->prependFile( "/js/jPlayer/jquery.jplayer.min.js");
$this->headScript()->prependFile( "//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js");
$this->headScript()->appendFile( "/js/main.js?{$version}");

$this->headLink()->appendStylesheet("http://fonts.googleapis.com/css?family=Ruslan+Display&subset=latin,cyrillic-ext");
$this->headLink()->appendStylesheet("/css/main.css?{$version}");

$this->headTitle($this->translate('menu.index'));
$this->headTitle()->setSeparator(' / ');


echo $this->doctype();
?>
<html>
	<head>
		<?= $this->headMeta(); ?>
		<?= $this->headTitle(); ?>
		<?= $this->render('counters.phtml'); ?>
		<link rel="icon" href="/favicon.ico" type="image/x-icon"/>
		<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon"/>
		<link rel="author" href="/humans.txt" />
		<?= $this->headLink(); ?>
		<!--[if lt IE 9]>
			<script src="/js/html5shiv.js"></script>
			<link type="text/css" rel="stylesheet" media="screen" href="/css/style_less_ie8.css">
		<![endif]-->
	</head>
	<body>
		<div class="wrapper">
			<header class="header">
				<div class="lang-block">
					<a class="lang-ru" href="<?php echo $this->url(array('lang' => 'ru')) ?>"></a>
					<a class="lang-en" href="<?php echo $this->url(array('lang' => 'en')) ?>"></a>
				</div>

				<? if( Zend_Controller_Action_HelperBroker::getStaticHelper('CheckAccess')->moderAccess() ): ?>
						<aside class="login-status">
							я модератор
							<a class="logout" href="<?= $this->url(array(), 'logout') ?>">
							</a>
						</aside>
				<? endif; ?>
				<a class="donate" href="<?= $this->url(array(), 'staticDonate') ?>">
						<?= $this->translate('title.index.donate'); ?>
				</a>
				<aside class="out-links-block">
					<a rel="nofollow" target="_blank" href="http://www.youtube.com/user/ABelkin?feature=watch" class="out-links out-link-youtube"></a>
					<a rel="nofollow" target="_blank" href="http://vk.com/club662700" class="out-links out-link-vk"></a>
					<a rel="nofollow" target="_blank" href="http://otavae.kroogi.ru" class="out-links out-link-kroogi"></a>
					<a rel="nofollow" target="_blank" href="http://myspace.com/otavae" class="out-links out-link-myspace"></a>
				</aside>

				<a href="<?php echo $this->url(array(), 'staticIndex') ?>">
					<img src="/img/otava_logo_main.png" class="logo">
				</a>

			</header>
			<div class="menu-block">
				<nav class="menu-links">
					<li><a href="<?= $this->url(array(), 'staticIndex') ?>"><?= $this->translate('menu.index'); ?></a></li>
					<li><a href="<?= $this->url(array(), 'staticNews') ?>"><?= $this->translate('menu.news'); ?></a></li>
					<li><a href="<?= $this->url(array(), 'staticConcert') ?>"><?= $this->translate('menu.concerts'); ?></a></li>
					<li><a href="<?= $this->url(array(), 'staticBand') ?>"><?= $this->translate('menu.band'); ?></a></li>
					<li><a href="<?= $this->url(array(), 'staticAudio') ?>"><?= $this->translate('menu.audio'); ?></a></li>
					<li><a href="<?= $this->url(array(), 'staticVideo') ?>"><?= $this->translate('menu.video'); ?></a></li>
					<li><a href="<?= $this->url(array(), 'staticGuestbook') ?>"><?= $this->translate('menu.guestbook'); ?></a></li>
					<li><a href="<?= $this->url(array(), 'staticContacts') ?>"><?= $this->translate('menu.contacts'); ?></a></li>
				</nav>
			</div>

			<div class="content">
				<?= $this->layout()->content; ?>
			</div>
			<div class="push"></div>
		</div>

		<div class="footer">
			<footer class="footer-block">
				<div>
					© Эйдук И.В. 2013
				</div>
				<a class="humans-txt" href="/humans.txt"></a>
			</footer>
		</div>

		<?= $this->headScript(); ?>
	</body>
</html>