<?php

$this->headMeta()
		->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8')
		->appendHttpEquiv('Content-Language', 'ru-RU')
		->appendName('description', "описание" )
		->appendName('keywords', "кейворды");

$version = $this->cacheVersion();

$this->headScript()->prependFile( "/js/main.js?{$version}");
$this->headLink()->prependStylesheet("/css/main.css?{$version}");

$this->headTitle('тайтл');

echo $this->doctype();
?>
<html>
	<head>
		<?php echo $this->headMeta(); ?>
		<?php echo $this->headTitle(); ?>
		<?php echo $this->render('counters.phtml'); ?>
		<link rel="icon" href="/img/favicon.ico" type="image/x-icon"/>
		<link rel="shortcut icon" href="/img/favicon.ico" type="image/x-icon"/>
		<link rel="author" href="/humans.txt" />
		<?php echo $this->headLink(); ?>
	</head>
	<body>
		<div id="header">
			<noscript>
				 Для корректной работы сайта необходимо включить JavaScript
			</noscript>
			<!--[if lte IE 7]>
				<p class="alert">К сожалению ваш браузер устарел и не поддерживается данным проектом. Пожалуйста обновитесь.</p>
			<![endif]-->
			хедер
		</div>

		<div id="content">
			<?php echo $this->layout()->content; ?>
		</div>

		<div id="footer">
			копирайты итд
		</div>

		<?php echo $this->headScript(); ?>
	</body>
</html>