name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Deploy
      run: |
        pip install Fabric3
        fab -H ${{secrets.DESTINATION_HOST}} -u ${{secrets.SSH_USER}} -p ${{secrets.SSH_PASS}} deploy
